DECLARE
	N VARCHAR2(10):='&N';
	P VARCHAR2(10):=' ';
	I NUMBER(20);
BEGIN
	DBMS_OUTPUT.PUT_LINE(length(N));
	FOR I IN 1..length(N)
	LOOP
		P:=LPAD(P,LENGTH(P)+1,SUBSTR(N,I,1));
		
	END LOOP;
	DBMS_OUTPUT.PUT_LINE('REVERSED STRING:'||P);	
END;
/
	
	
