--AT FIRST CREATE THE TABLE FROM SQL WITH ANY ATTRIBUTE NAME
CREATE OR REPLACE TRIGGER RATING_TRIGGER AFTER UPDATE OF RATING ON SAILOR FOR EACH ROW
DECLARE
BEGIN
	IF UPDATING THEN
		INSERT INTO SAILOR_TRIGGER VALUES(:OLD.SID,:OLD.RATING,:NEW.RATING,SYSDATE);
	END IF;
END;
/
